# Generated by Django 3.1.7 on 2021-03-01 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Countries grouping',
            },
        ),
        migrations.CreateModel(
            name='DataSharingLifeCycleStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data sharing lifecycle stages',
            },
        ),
        migrations.CreateModel(
            name='DataTypeFocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data type focuses',
            },
        ),
        migrations.CreateModel(
            name='GlobalScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Global scopes',
            },
        ),
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Perspectives',
            },
        ),
        migrations.CreateModel(
            name='ResearchDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Research designs',
            },
        ),
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Research fields',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Resource types',
            },
        ),
        migrations.CreateModel(
            name='SpecificTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Specific topics',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, max_length=350, null=True, upload_to='uploads/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('country_grouping', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.countrygrouping')),
                ('data_sharing_life_cycle_stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.datasharinglifecyclestage')),
                ('data_type_focus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.datatypefocus')),
                ('global_scope', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.globalscope')),
                ('perspective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.perspective')),
                ('research_design', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.researchdesign')),
                ('research_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.researchfield')),
                ('resource_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.resourcetype')),
                ('specific_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.specifictopic')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tag')),
            ],
            options={
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.AddField(
            model_name='countrygrouping',
            name='global_scope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.globalscope'),
        ),
    ]
