# Generated by Django 3.1.7 on 2021-03-01 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210301_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='global_scope',
        ),
        migrations.AddField(
            model_name='resource',
            name='global_scope',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.globalscope'),
        ),
    ]
