# Generated by Django 3.1.7 on 2021-03-01 22:23

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210301_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='country_grouping',
        ),
        migrations.AddField(
            model_name='resource',
            name='country_grouping',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='global_scope', chained_model_field='global_scope', default=1, on_delete=django.db.models.deletion.CASCADE, show_all=True, to='app.countrygrouping'),
            preserve_default=False,
        ),
    ]
