# Generated by Django 3.1.7 on 2021-03-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210301_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='country_grouping',
        ),
        migrations.AddField(
            model_name='resource',
            name='country_grouping',
            field=models.ManyToManyField(default=1, to='app.CountryGrouping'),
        ),
    ]
