# Generated by Django 3.1.7 on 2021-03-01 22:32

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210301_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='country_grouping',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='global_scope', chained_model_field='global_scope', horizontal=True, to='app.CountryGrouping', verbose_name='country_grouping'),
        ),
    ]
