# Generated by Django 3.1.7 on 2021-03-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210301_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'permissions': (('can_edit_post', 'Can edit post'),), 'verbose_name_plural': 'Resources'},
        ),
    ]
