# Generated by Django 3.1.7 on 2021-03-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210302_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='perspective',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='research_design',
        ),
        migrations.DeleteModel(
            name='Perspective',
        ),
        migrations.DeleteModel(
            name='ResearchDesign',
        ),
    ]
