# Generated by Django 3.1.7 on 2021-03-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210302_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='title',
        ),
    ]
