# Generated by Django 3.1.7 on 2021-03-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210302_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='data_sharing_life_cycle_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.datasharinglifecyclestage'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='data_type_focus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.datatypefocus'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='global_scope',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.globalscope'),
        ),
    ]
