# Generated by Django 3.1.7 on 2021-03-02 16:23

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210302_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalScope',
            new_name='GeographicalScope',
        ),
        migrations.AlterModelOptions(
            name='geographicalscope',
            options={'verbose_name_plural': 'Geographical scope'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name_plural': 'Resources'},
        ),
        migrations.RenameField(
            model_name='countrygrouping',
            old_name='global_scope',
            new_name='geographical_scope',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='global_scope',
            new_name='geographical_scope',
        ),
        migrations.AlterField(
            model_name='resource',
            name='country_grouping',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='geographical_scope', chained_model_field='geographical_scope', horizontal=True, to='app.CountryGrouping', verbose_name='Countries grouping'),
        ),
    ]
