# Generated by Django 3.1.7 on 2021-04-19 10:34

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210302_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Data Types',
            },
        ),
        migrations.CreateModel(
            name='DataTypeSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('data_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.datatype')),
            ],
            options={
                'verbose_name_plural': 'Data types subgroups',
            },
        ),
        migrations.CreateModel(
            name='StageInDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stage in DS',
            },
        ),
        migrations.RemoveField(
            model_name='resource',
            name='data_sharing_life_cycle_stage',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='data_type_focus',
        ),
        migrations.AlterField(
            model_name='countrygrouping',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='geographicalscope',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.DeleteModel(
            name='DataSharingLifeCycleStage',
        ),
        migrations.DeleteModel(
            name='DataTypeFocus',
        ),
        migrations.AddField(
            model_name='resource',
            name='data_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.datatype'),
        ),
        migrations.AddField(
            model_name='resource',
            name='data_type_sub',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='data_type', chained_model_field='data_type', horizontal=True, to='app.DataTypeSub', verbose_name='Data type subgroups'),
        ),
        migrations.AddField(
            model_name='resource',
            name='stage_in_ds',
            field=models.ManyToManyField(to='app.StageInDS'),
        ),
    ]
