# Generated by Django 3.1.7 on 2021-04-27 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_is_approved'),
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggingresource',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
        ),
    ]
