# Generated by Django 3.1.7 on 2021-05-03 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210503_1557'),
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggingresource',
            name='resource',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
        ),
    ]
