# Generated by Django 3.1.7 on 2021-05-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggingresource',
            options={'verbose_name_plural': 'Tagging section'},
        ),
    ]
