# Generated by Django 3.1.7 on 2021-04-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0003_auto_20210427_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggingresource',
            old_name='country_grouping',
            new_name='countries_grouping',
        ),
        migrations.RenameField(
            model_name='taggingresource',
            old_name='data_type_sub',
            new_name='data_type_subs',
        ),
    ]
