# Generated by Django 3.1.7 on 2021-10-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20211027_0958'),
        ('tagging', '0003_auto_20211027_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggingresource',
            name='research_field',
            field=models.ManyToManyField(to='categories.ResearchField'),
        ),
        migrations.AlterField(
            model_name='taggingresource',
            name='resource_type',
            field=models.ManyToManyField(to='categories.ResourceType'),
        ),
        migrations.AlterField(
            model_name='taggingresource',
            name='sensitive_data',
            field=models.ManyToManyField(to='categories.SensitiveData'),
        ),
        migrations.AlterField(
            model_name='taggingresource',
            name='specific_topics',
            field=models.ManyToManyField(to='categories.SpecificTopic'),
        ),
    ]
