# Generated by Django 3.1.7 on 2021-05-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Data types',
            },
        ),
        migrations.CreateModel(
            name='GeographicalScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Geographical scope',
            },
        ),
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Research fields',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Resource types',
            },
        ),
        migrations.CreateModel(
            name='SpecificTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '6. Specific topics',
            },
        ),
        migrations.CreateModel(
            name='StageInDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Stage in data sharing life cycle',
            },
        ),
        migrations.CreateModel(
            name='DataTypeSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.datatype')),
            ],
            options={
                'verbose_name_plural': 'Data types subgroups',
            },
        ),
        migrations.CreateModel(
            name='CountryGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('geographical_scope', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.geographicalscope')),
            ],
            options={
                'verbose_name_plural': 'Countries grouping',
            },
        ),
    ]
