# Generated by Django 3.1.7 on 2021-04-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatype',
            options={'verbose_name_plural': '3. Data types'},
        ),
        migrations.AlterModelOptions(
            name='geographicalscope',
            options={'verbose_name_plural': '5. Geographical scope'},
        ),
        migrations.AlterModelOptions(
            name='researchfield',
            options={'verbose_name_plural': '2. Research fields'},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'verbose_name_plural': '1. Resource types'},
        ),
        migrations.AlterModelOptions(
            name='specifictopic',
            options={'verbose_name_plural': '6. Specific topics'},
        ),
        migrations.AlterModelOptions(
            name='stageinds',
            options={'verbose_name_plural': '4. Stage in data sharing life cycle'},
        ),
    ]
