# Generated by Django 3.1.7 on 2021-10-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Sensitive data',
            },
        ),
        migrations.AlterModelOptions(
            name='datatype',
            options={'verbose_name_plural': '4. Data types'},
        ),
        migrations.AlterModelOptions(
            name='geographicalscope',
            options={'verbose_name_plural': '6. Geographical scope'},
        ),
        migrations.AlterModelOptions(
            name='researchfield',
            options={'verbose_name_plural': '3. Research fields'},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'verbose_name_plural': '2. Resource types'},
        ),
        migrations.AlterModelOptions(
            name='specifictopic',
            options={'verbose_name_plural': '7. Specific topics'},
        ),
        migrations.AlterModelOptions(
            name='stageinds',
            options={'verbose_name_plural': '5. Stage in data sharing life cycle'},
        ),
    ]
