# Generated by Django 3.1.7 on 2021-05-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentmanager',
            options={'verbose_name_plural': '2. Content managers'},
        ),
        migrations.AlterModelOptions(
            name='projectcoordinator',
            options={'verbose_name_plural': '1. Project coordinators'},
        ),
        migrations.AlterModelOptions(
            name='tagginguser',
            options={'verbose_name_plural': '3. Tagging users'},
        ),
    ]
