# Generated by Django 3.1.7 on 2021-04-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('access_to_categories', 'Access to the Categories sections'), ('access_to_resources', 'Access to the Resources sections'), ('access_to_tags', 'Access to the Tags sections'), ('access_to_users_and_groups', 'Access to the Users and Groups sections'), ('add_categories', 'Allows to add new categories parameters'), ('edit_categories', 'Allows to edit categories parameters'), ('remove_categories', 'Allows to remove categories parameters'), ('add_resources', 'Allows to add new resources'), ('edit_resources', 'Allows to edit resources'), ('remove_resources', 'Allows to remove resources'), ('add_tags', 'Allows to add new tags'), ('edit_tags', 'Allows to edit tags'), ('remove_tags', 'Allows to remove tags'), ('add_users', 'Allows to add new users'), ('edit_users', 'Allows to edit users'), ('remove_users', 'Allows to remove users'))},
        ),
    ]
