# Generated by Django 3.1.7 on 2021-04-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0002_auto_20210422_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
