# Generated by Django 3.1.7 on 2021-05-09 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_management', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('short_title', models.CharField(blank=True, max_length=250, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(default='Unknown')),
                ('year_of_publication', models.IntegerField(default=0)),
                ('doi', models.CharField(blank=True, max_length=175, null=True, verbose_name='DOI')),
                ('url', models.URLField(max_length=1000, verbose_name='URL')),
                ('resource_file', models.FileField(blank=True, max_length=450, null=True, upload_to='uploads/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.language')),
                ('tagging_persons', models.ManyToManyField(related_name='tagging_persons', to='users_management.TaggingUser')),
            ],
            options={
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Resource types',
            },
        ),
        migrations.CreateModel(
            name='ResourceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_for_tagging', models.BooleanField(blank=True, default=False)),
                ('is_tagged', models.BooleanField(blank=True, default=False)),
                ('waiting_for_approval', models.BooleanField(blank=True, default=False)),
                ('is_approved', models.BooleanField(blank=True, default=False)),
                ('status_description', models.CharField(blank=True, default='None', max_length=75)),
                ('resource', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
            options={
                'verbose_name_plural': 'Resources statuses',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='type_of_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resourcetype'),
        ),
    ]
