# Generated by Django 3.1.7 on 2021-05-03 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_management', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
                ('resource_file', models.FileField(blank=True, max_length=450, null=True, upload_to='uploads/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current_status', models.CharField(blank=True, default='Waiting for tagging', max_length=75)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('tagging_persons', models.ManyToManyField(related_name='tagging_persons', to='users_management.TaggingUser')),
            ],
            options={
                'verbose_name_plural': 'Resources',
            },
        ),
    ]
