# Generated by Django 3.1.7 on 2021-05-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='doi',
            field=models.CharField(blank=True, max_length=175, null=True, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='short_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='URL'),
        ),
    ]
