# Generated by Django 3.1.7 on 2021-09-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourceType',
            new_name='TypeOfResource',
        ),
    ]
