# Generated by Django 3.1.7 on 2021-04-22 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagging', '0001_initial'),
        ('categories', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='country_grouping',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='geographical_scope', chained_model_field='geographical_scope', horizontal=True, to='categories.CountryGrouping', verbose_name='Countries grouping'),
        ),
        migrations.AddField(
            model_name='resource',
            name='data_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.datatype'),
        ),
        migrations.AddField(
            model_name='resource',
            name='data_type_sub',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='data_type', chained_model_field='data_type', horizontal=True, to='categories.DataTypeSub', verbose_name='Data type subgroups'),
        ),
        migrations.AddField(
            model_name='resource',
            name='geographical_scope',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.geographicalscope'),
        ),
        migrations.AddField(
            model_name='resource',
            name='research_field',
            field=models.ManyToManyField(to='categories.ResearchField'),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.ManyToManyField(to='categories.ResourceType'),
        ),
        migrations.AddField(
            model_name='resource',
            name='specific_topic',
            field=models.ManyToManyField(to='categories.SpecificTopic'),
        ),
        migrations.AddField(
            model_name='resource',
            name='stage_in_ds',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.stageinds', verbose_name='Stage in data sharing life cycle'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tagging_persons',
            field=models.ManyToManyField(related_name='tagging_persons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tagging.Tag'),
        ),
    ]
