# Generated by Django 3.1.7 on 2021-04-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='is_approved',
        ),
    ]
