# Generated by Django 3.1.7 on 2021-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='year_of_publication',
            field=models.IntegerField(default=1950),
        ),
    ]
