# Generated by Django 3.1.7 on 2021-05-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210503_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='current_status',
            field=models.CharField(blank=True, default='None', max_length=75),
        ),
    ]
