# Generated by Django 3.1.7 on 2021-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210422_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='tags',
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
