# Generated by Django 3.1.7 on 2021-05-04 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20210504_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='current_status',
        ),
        migrations.CreateModel(
            name='ResourceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_for_tagging', models.BooleanField(blank=True, default=False)),
                ('is_tagged', models.BooleanField(blank=True, default=False)),
                ('waiting_for_approval', models.BooleanField(blank=True, default=False)),
                ('is_approved', models.BooleanField(blank=True, default=False)),
                ('status_description', models.CharField(blank=True, default='None', max_length=75)),
                ('resource', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
            options={
                'verbose_name_plural': 'Resources statuses',
            },
        ),
    ]
