# Generated by Django 3.1.7 on 2021-04-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20210422_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='tags',
        ),
    ]
