# Generated by Django 3.1.7 on 2021-05-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20210504_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Resource types',
            },
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='description',
            new_name='abstract',
        ),
        migrations.AddField(
            model_name='resource',
            name='authors',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='resource',
            name='doi',
            field=models.CharField(blank=True, max_length=175, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='shot_title',
            field=models.CharField(blank=True, max_length=175, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='year_of_publication',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='resource',
            name='language',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.language'),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resourcetype'),
        ),
    ]
