# Generated by Django 3.1.7 on 2021-04-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_remove_resource_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='is_approved',
        ),
    ]
