# Generated by Django 3.1.7 on 2021-05-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20210505_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.language'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type_of_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resourcetype'),
        ),
    ]
